server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    basic:
      enabled: false  
    formLogin:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization-server:9000/oauth2/jwks
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service-route
          # lb://CATALOG-SERVICE - балансировка на инстансы, найденные в Eureka
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
        
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: borrowing-service-route
          uri: lb://BORROWING-SERVICE
          predicates:
            - Path=/api/borrowing/**